// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
package protocol APIProtocol: Sendable {
    /// Create or update an SDK user
    ///
    /// Registers a user and returns a session token for authenticated operations.
    ///
    /// - Remark: HTTP `POST /users`.
    /// - Remark: Generated from `#/paths//users/post(createUser)`.
    func createUser(_ input: Operations.createUser.Input) async throws -> Operations.createUser.Output
    /// List feature requests
    ///
    /// - Remark: HTTP `GET /requests`.
    /// - Remark: Generated from `#/paths//requests/get(listRequests)`.
    func listRequests(_ input: Operations.listRequests.Input) async throws -> Operations.listRequests.Output
    /// Submit a new feature request
    ///
    /// - Remark: HTTP `POST /requests`.
    /// - Remark: Generated from `#/paths//requests/post(submitRequest)`.
    func submitRequest(_ input: Operations.submitRequest.Input) async throws -> Operations.submitRequest.Output
    /// Search requests by title
    ///
    /// - Remark: HTTP `GET /requests/search`.
    /// - Remark: Generated from `#/paths//requests/search/get(searchRequests)`.
    func searchRequests(_ input: Operations.searchRequests.Input) async throws -> Operations.searchRequests.Output
    /// Get a single feature request
    ///
    /// - Remark: HTTP `GET /requests/{requestId}`.
    /// - Remark: Generated from `#/paths//requests/{requestId}/get(getRequest)`.
    func getRequest(_ input: Operations.getRequest.Input) async throws -> Operations.getRequest.Output
    /// Vote on a feature request
    ///
    /// - Remark: HTTP `POST /requests/{requestId}/vote`.
    /// - Remark: Generated from `#/paths//requests/{requestId}/vote/post(vote)`.
    func vote(_ input: Operations.vote.Input) async throws -> Operations.vote.Output
    /// List decline reasons for the app
    ///
    /// - Remark: HTTP `GET /decline-reasons`.
    /// - Remark: Generated from `#/paths//decline-reasons/get(listDeclineReasons)`.
    func listDeclineReasons(_ input: Operations.listDeclineReasons.Input) async throws -> Operations.listDeclineReasons.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// Create or update an SDK user
    ///
    /// Registers a user and returns a session token for authenticated operations.
    ///
    /// - Remark: HTTP `POST /users`.
    /// - Remark: Generated from `#/paths//users/post(createUser)`.
    package func createUser(
        headers: Operations.createUser.Input.Headers = .init(),
        body: Operations.createUser.Input.Body
    ) async throws -> Operations.createUser.Output {
        try await createUser(Operations.createUser.Input(
            headers: headers,
            body: body
        ))
    }
    /// List feature requests
    ///
    /// - Remark: HTTP `GET /requests`.
    /// - Remark: Generated from `#/paths//requests/get(listRequests)`.
    package func listRequests(
        query: Operations.listRequests.Input.Query = .init(),
        headers: Operations.listRequests.Input.Headers = .init()
    ) async throws -> Operations.listRequests.Output {
        try await listRequests(Operations.listRequests.Input(
            query: query,
            headers: headers
        ))
    }
    /// Submit a new feature request
    ///
    /// - Remark: HTTP `POST /requests`.
    /// - Remark: Generated from `#/paths//requests/post(submitRequest)`.
    package func submitRequest(
        headers: Operations.submitRequest.Input.Headers = .init(),
        body: Operations.submitRequest.Input.Body
    ) async throws -> Operations.submitRequest.Output {
        try await submitRequest(Operations.submitRequest.Input(
            headers: headers,
            body: body
        ))
    }
    /// Search requests by title
    ///
    /// - Remark: HTTP `GET /requests/search`.
    /// - Remark: Generated from `#/paths//requests/search/get(searchRequests)`.
    package func searchRequests(
        query: Operations.searchRequests.Input.Query,
        headers: Operations.searchRequests.Input.Headers = .init()
    ) async throws -> Operations.searchRequests.Output {
        try await searchRequests(Operations.searchRequests.Input(
            query: query,
            headers: headers
        ))
    }
    /// Get a single feature request
    ///
    /// - Remark: HTTP `GET /requests/{requestId}`.
    /// - Remark: Generated from `#/paths//requests/{requestId}/get(getRequest)`.
    package func getRequest(
        path: Operations.getRequest.Input.Path,
        headers: Operations.getRequest.Input.Headers = .init()
    ) async throws -> Operations.getRequest.Output {
        try await getRequest(Operations.getRequest.Input(
            path: path,
            headers: headers
        ))
    }
    /// Vote on a feature request
    ///
    /// - Remark: HTTP `POST /requests/{requestId}/vote`.
    /// - Remark: Generated from `#/paths//requests/{requestId}/vote/post(vote)`.
    package func vote(
        path: Operations.vote.Input.Path,
        headers: Operations.vote.Input.Headers = .init(),
        body: Operations.vote.Input.Body
    ) async throws -> Operations.vote.Output {
        try await vote(Operations.vote.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// List decline reasons for the app
    ///
    /// - Remark: HTTP `GET /decline-reasons`.
    /// - Remark: Generated from `#/paths//decline-reasons/get(listDeclineReasons)`.
    package func listDeclineReasons(headers: Operations.listDeclineReasons.Input.Headers = .init()) async throws -> Operations.listDeclineReasons.Output {
        try await listDeclineReasons(Operations.listDeclineReasons.Input(headers: headers))
    }
}

/// Server URLs defined in the OpenAPI document.
package enum Servers {
    /// Production
    package enum Server1 {
        /// Production
        package static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "https://kstb23efj8.execute-api.us-east-1.amazonaws.com",
                variables: []
            )
        }
    }
    /// Production
    @available(*, deprecated, renamed: "Servers.Server1.url")
    package static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "https://kstb23efj8.execute-api.us-east-1.amazonaws.com",
            variables: []
        )
    }
    /// Development
    package enum Server2 {
        /// Development
        package static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "https://urvselrxwj.execute-api.us-east-1.amazonaws.com",
                variables: []
            )
        }
    }
    /// Development
    @available(*, deprecated, renamed: "Servers.Server2.url")
    package static func server2() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "https://urvselrxwj.execute-api.us-east-1.amazonaws.com",
            variables: []
        )
    }
}

/// Types generated from the components section of the OpenAPI document.
package enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    package enum Schemas {
        /// - Remark: Generated from `#/components/schemas/SortOrder`.
        @frozen package enum SortOrder: String, Codable, Hashable, Sendable, CaseIterable {
            case recent = "recent"
            case top = "top"
        }
        /// - Remark: Generated from `#/components/schemas/RequestStatus`.
        @frozen package enum RequestStatus: String, Codable, Hashable, Sendable, CaseIterable {
            case open = "open"
            case planned = "planned"
            case in_progress = "in_progress"
            case shipped = "shipped"
            case declined = "declined"
        }
        /// - Remark: Generated from `#/components/schemas/RequestSource`.
        @frozen package enum RequestSource: String, Codable, Hashable, Sendable, CaseIterable {
            case sdk = "sdk"
            case console = "console"
        }
        /// - Remark: Generated from `#/components/schemas/Request`.
        package struct Request: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Request/id`.
            package var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/Request/appId`.
            package var appId: Swift.String
            /// - Remark: Generated from `#/components/schemas/Request/authorId`.
            package var authorId: Swift.String?
            /// - Remark: Generated from `#/components/schemas/Request/title`.
            package var title: Swift.String
            /// - Remark: Generated from `#/components/schemas/Request/body`.
            package var body: Swift.String
            /// - Remark: Generated from `#/components/schemas/Request/status`.
            package var status: Components.Schemas.RequestStatus
            /// - Remark: Generated from `#/components/schemas/Request/source`.
            package var source: Components.Schemas.RequestSource
            /// - Remark: Generated from `#/components/schemas/Request/score`.
            package var score: Swift.Int
            /// - Remark: Generated from `#/components/schemas/Request/mergedIntoId`.
            package var mergedIntoId: Swift.String?
            /// - Remark: Generated from `#/components/schemas/Request/declineReason`.
            package var declineReason: Swift.String?
            /// - Remark: Generated from `#/components/schemas/Request/declineReasonId`.
            package var declineReasonId: Swift.String?
            /// - Remark: Generated from `#/components/schemas/Request/declineReasonLabel`.
            package var declineReasonLabel: Swift.String?
            /// - Remark: Generated from `#/components/schemas/Request/authorDisplayName`.
            package var authorDisplayName: Swift.String
            /// - Remark: Generated from `#/components/schemas/Request/authorExternalUserId`.
            package var authorExternalUserId: Swift.String?
            /// - Remark: Generated from `#/components/schemas/Request/authorAvatarUrl`.
            package var authorAvatarUrl: Swift.String?
            /// - Remark: Generated from `#/components/schemas/Request/createdAt`.
            package var createdAt: Foundation.Date
            /// - Remark: Generated from `#/components/schemas/Request/updatedAt`.
            package var updatedAt: Foundation.Date
            /// Creates a new `Request`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - appId:
            ///   - authorId:
            ///   - title:
            ///   - body:
            ///   - status:
            ///   - source:
            ///   - score:
            ///   - mergedIntoId:
            ///   - declineReason:
            ///   - declineReasonId:
            ///   - declineReasonLabel:
            ///   - authorDisplayName:
            ///   - authorExternalUserId:
            ///   - authorAvatarUrl:
            ///   - createdAt:
            ///   - updatedAt:
            package init(
                id: Swift.String,
                appId: Swift.String,
                authorId: Swift.String? = nil,
                title: Swift.String,
                body: Swift.String,
                status: Components.Schemas.RequestStatus,
                source: Components.Schemas.RequestSource,
                score: Swift.Int,
                mergedIntoId: Swift.String? = nil,
                declineReason: Swift.String? = nil,
                declineReasonId: Swift.String? = nil,
                declineReasonLabel: Swift.String? = nil,
                authorDisplayName: Swift.String,
                authorExternalUserId: Swift.String? = nil,
                authorAvatarUrl: Swift.String? = nil,
                createdAt: Foundation.Date,
                updatedAt: Foundation.Date
            ) {
                self.id = id
                self.appId = appId
                self.authorId = authorId
                self.title = title
                self.body = body
                self.status = status
                self.source = source
                self.score = score
                self.mergedIntoId = mergedIntoId
                self.declineReason = declineReason
                self.declineReasonId = declineReasonId
                self.declineReasonLabel = declineReasonLabel
                self.authorDisplayName = authorDisplayName
                self.authorExternalUserId = authorExternalUserId
                self.authorAvatarUrl = authorAvatarUrl
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            package enum CodingKeys: String, CodingKey {
                case id
                case appId
                case authorId
                case title
                case body
                case status
                case source
                case score
                case mergedIntoId
                case declineReason
                case declineReasonId
                case declineReasonLabel
                case authorDisplayName
                case authorExternalUserId
                case authorAvatarUrl
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/PaginatedRequests`.
        package struct PaginatedRequests: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/PaginatedRequests/data`.
            package var data: [Components.Schemas.Request]
            /// - Remark: Generated from `#/components/schemas/PaginatedRequests/cursor`.
            package var cursor: Swift.String?
            /// - Remark: Generated from `#/components/schemas/PaginatedRequests/hasMore`.
            package var hasMore: Swift.Bool
            /// Creates a new `PaginatedRequests`.
            ///
            /// - Parameters:
            ///   - data:
            ///   - cursor:
            ///   - hasMore:
            package init(
                data: [Components.Schemas.Request],
                cursor: Swift.String? = nil,
                hasMore: Swift.Bool
            ) {
                self.data = data
                self.cursor = cursor
                self.hasMore = hasMore
            }
            package enum CodingKeys: String, CodingKey {
                case data
                case cursor
                case hasMore
            }
        }
        /// - Remark: Generated from `#/components/schemas/User`.
        package struct User: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/User/userId`.
            package var userId: Swift.String
            /// - Remark: Generated from `#/components/schemas/User/sessionToken`.
            package var sessionToken: Swift.String
            /// - Remark: Generated from `#/components/schemas/User/externalUserId`.
            package var externalUserId: Swift.String
            /// - Remark: Generated from `#/components/schemas/User/displayName`.
            package var displayName: Swift.String
            /// - Remark: Generated from `#/components/schemas/User/avatarUrl`.
            package var avatarUrl: Swift.String?
            /// Creates a new `User`.
            ///
            /// - Parameters:
            ///   - userId:
            ///   - sessionToken:
            ///   - externalUserId:
            ///   - displayName:
            ///   - avatarUrl:
            package init(
                userId: Swift.String,
                sessionToken: Swift.String,
                externalUserId: Swift.String,
                displayName: Swift.String,
                avatarUrl: Swift.String? = nil
            ) {
                self.userId = userId
                self.sessionToken = sessionToken
                self.externalUserId = externalUserId
                self.displayName = displayName
                self.avatarUrl = avatarUrl
            }
            package enum CodingKeys: String, CodingKey {
                case userId
                case sessionToken
                case externalUserId
                case displayName
                case avatarUrl
            }
        }
        /// - Remark: Generated from `#/components/schemas/Vote`.
        package struct Vote: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Vote/id`.
            package var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/Vote/requestId`.
            package var requestId: Swift.String
            /// - Remark: Generated from `#/components/schemas/Vote/userId`.
            package var userId: Swift.String
            /// - Remark: Generated from `#/components/schemas/Vote/value`.
            package var value: Swift.Int
            /// - Remark: Generated from `#/components/schemas/Vote/createdAt`.
            package var createdAt: Foundation.Date
            /// - Remark: Generated from `#/components/schemas/Vote/updatedAt`.
            package var updatedAt: Foundation.Date
            /// Creates a new `Vote`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - requestId:
            ///   - userId:
            ///   - value:
            ///   - createdAt:
            ///   - updatedAt:
            package init(
                id: Swift.String,
                requestId: Swift.String,
                userId: Swift.String,
                value: Swift.Int,
                createdAt: Foundation.Date,
                updatedAt: Foundation.Date
            ) {
                self.id = id
                self.requestId = requestId
                self.userId = userId
                self.value = value
                self.createdAt = createdAt
                self.updatedAt = updatedAt
            }
            package enum CodingKeys: String, CodingKey {
                case id
                case requestId
                case userId
                case value
                case createdAt
                case updatedAt
            }
        }
        /// - Remark: Generated from `#/components/schemas/DeclineReason`.
        package struct DeclineReason: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/DeclineReason/id`.
            package var id: Swift.String
            /// - Remark: Generated from `#/components/schemas/DeclineReason/appId`.
            package var appId: Swift.String
            /// - Remark: Generated from `#/components/schemas/DeclineReason/label`.
            package var label: Swift.String
            /// - Remark: Generated from `#/components/schemas/DeclineReason/isDefault`.
            package var isDefault: Swift.Bool
            /// Creates a new `DeclineReason`.
            ///
            /// - Parameters:
            ///   - id:
            ///   - appId:
            ///   - label:
            ///   - isDefault:
            package init(
                id: Swift.String,
                appId: Swift.String,
                label: Swift.String,
                isDefault: Swift.Bool
            ) {
                self.id = id
                self.appId = appId
                self.label = label
                self.isDefault = isDefault
            }
            package enum CodingKeys: String, CodingKey {
                case id
                case appId
                case label
                case isDefault
            }
        }
        /// - Remark: Generated from `#/components/schemas/ApiError`.
        package struct ApiError: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ApiError/statusCode`.
            package var statusCode: Swift.Int
            /// - Remark: Generated from `#/components/schemas/ApiError/error`.
            package var error: Swift.String
            /// - Remark: Generated from `#/components/schemas/ApiError/message`.
            package var message: Swift.String
            /// Creates a new `ApiError`.
            ///
            /// - Parameters:
            ///   - statusCode:
            ///   - error:
            ///   - message:
            package init(
                statusCode: Swift.Int,
                error: Swift.String,
                message: Swift.String
            ) {
                self.statusCode = statusCode
                self.error = error
                self.message = message
            }
            package enum CodingKeys: String, CodingKey {
                case statusCode
                case error
                case message
            }
        }
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    package enum Parameters {}
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    package enum RequestBodies {}
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    package enum Responses {
        package struct BadRequest: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/BadRequest/content`.
            @frozen package enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/BadRequest/content/application\/json`.
                case json(Components.Schemas.ApiError)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                package var json: Components.Schemas.ApiError {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            package var body: Components.Responses.BadRequest.Body
            /// Creates a new `BadRequest`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            package init(body: Components.Responses.BadRequest.Body) {
                self.body = body
            }
        }
        package struct Unauthorized: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/Unauthorized/content`.
            @frozen package enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/Unauthorized/content/application\/json`.
                case json(Components.Schemas.ApiError)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                package var json: Components.Schemas.ApiError {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            package var body: Components.Responses.Unauthorized.Body
            /// Creates a new `Unauthorized`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            package init(body: Components.Responses.Unauthorized.Body) {
                self.body = body
            }
        }
        package struct NotFound: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/NotFound/content`.
            @frozen package enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/NotFound/content/application\/json`.
                case json(Components.Schemas.ApiError)
                /// The associated value of the enum case if `self` is `.json`.
                ///
                /// - Throws: An error if `self` is not `.json`.
                /// - SeeAlso: `.json`.
                package var json: Components.Schemas.ApiError {
                    get throws {
                        switch self {
                        case let .json(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            package var body: Components.Responses.NotFound.Body
            /// Creates a new `NotFound`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            package init(body: Components.Responses.NotFound.Body) {
                self.body = body
            }
        }
    }
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    package enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
package enum Operations {
    /// Create or update an SDK user
    ///
    /// Registers a user and returns a session token for authenticated operations.
    ///
    /// - Remark: HTTP `POST /users`.
    /// - Remark: Generated from `#/paths//users/post(createUser)`.
    package enum createUser {
        package static let id: Swift.String = "createUser"
        package struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/users/POST/header`.
            package struct Headers: Sendable, Hashable {
                package var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.createUser.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                package init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.createUser.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            package var headers: Operations.createUser.Input.Headers
            /// - Remark: Generated from `#/paths/users/POST/requestBody`.
            @frozen package enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/users/POST/requestBody/json`.
                package struct jsonPayload: Codable, Hashable, Sendable {
                    /// - Remark: Generated from `#/paths/users/POST/requestBody/json/externalUserId`.
                    package var externalUserId: Swift.String
                    /// - Remark: Generated from `#/paths/users/POST/requestBody/json/displayName`.
                    package var displayName: Swift.String
                    /// - Remark: Generated from `#/paths/users/POST/requestBody/json/avatarUrl`.
                    package var avatarUrl: Swift.String?
                    /// Creates a new `jsonPayload`.
                    ///
                    /// - Parameters:
                    ///   - externalUserId:
                    ///   - displayName:
                    ///   - avatarUrl:
                    package init(
                        externalUserId: Swift.String,
                        displayName: Swift.String,
                        avatarUrl: Swift.String? = nil
                    ) {
                        self.externalUserId = externalUserId
                        self.displayName = displayName
                        self.avatarUrl = avatarUrl
                    }
                    package enum CodingKeys: String, CodingKey {
                        case externalUserId
                        case displayName
                        case avatarUrl
                    }
                }
                /// - Remark: Generated from `#/paths/users/POST/requestBody/content/application\/json`.
                case json(Operations.createUser.Input.Body.jsonPayload)
            }
            package var body: Operations.createUser.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            package init(
                headers: Operations.createUser.Input.Headers = .init(),
                body: Operations.createUser.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen package enum Output: Sendable, Hashable {
            package struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/users/POST/responses/200/content`.
                @frozen package enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/users/POST/responses/200/content/application\/json`.
                    case json(Components.Schemas.User)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    package var json: Components.Schemas.User {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                package var body: Operations.createUser.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                package init(body: Operations.createUser.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// User created or updated
            ///
            /// - Remark: Generated from `#/paths//users/post(createUser)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.createUser.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            package var ok: Operations.createUser.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Validation error
            ///
            /// - Remark: Generated from `#/paths//users/post(createUser)/responses/400`.
            ///
            /// HTTP response code: `400 badRequest`.
            case badRequest(Components.Responses.BadRequest)
            /// The associated value of the enum case if `self` is `.badRequest`.
            ///
            /// - Throws: An error if `self` is not `.badRequest`.
            /// - SeeAlso: `.badRequest`.
            package var badRequest: Components.Responses.BadRequest {
                get throws {
                    switch self {
                    case let .badRequest(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "badRequest",
                            response: self
                        )
                    }
                }
            }
            /// Missing or invalid authentication
            ///
            /// - Remark: Generated from `#/paths//users/post(createUser)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Components.Responses.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            package var unauthorized: Components.Responses.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen package enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            package init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            package var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            package static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// List feature requests
    ///
    /// - Remark: HTTP `GET /requests`.
    /// - Remark: Generated from `#/paths//requests/get(listRequests)`.
    package enum listRequests {
        package static let id: Swift.String = "listRequests"
        package struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/requests/GET/query`.
            package struct Query: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/requests/GET/query/sort`.
                package var sort: Components.Schemas.SortOrder?
                /// - Remark: Generated from `#/paths/requests/GET/query/status`.
                package var status: Components.Schemas.RequestStatus?
                /// - Remark: Generated from `#/paths/requests/GET/query/limit`.
                package var limit: Swift.Int?
                /// - Remark: Generated from `#/paths/requests/GET/query/cursor`.
                package var cursor: Swift.String?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - sort:
                ///   - status:
                ///   - limit:
                ///   - cursor:
                package init(
                    sort: Components.Schemas.SortOrder? = nil,
                    status: Components.Schemas.RequestStatus? = nil,
                    limit: Swift.Int? = nil,
                    cursor: Swift.String? = nil
                ) {
                    self.sort = sort
                    self.status = status
                    self.limit = limit
                    self.cursor = cursor
                }
            }
            package var query: Operations.listRequests.Input.Query
            /// - Remark: Generated from `#/paths/requests/GET/header`.
            package struct Headers: Sendable, Hashable {
                package var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.listRequests.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                package init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.listRequests.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            package var headers: Operations.listRequests.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - headers:
            package init(
                query: Operations.listRequests.Input.Query = .init(),
                headers: Operations.listRequests.Input.Headers = .init()
            ) {
                self.query = query
                self.headers = headers
            }
        }
        @frozen package enum Output: Sendable, Hashable {
            package struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/requests/GET/responses/200/content`.
                @frozen package enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/requests/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.PaginatedRequests)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    package var json: Components.Schemas.PaginatedRequests {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                package var body: Operations.listRequests.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                package init(body: Operations.listRequests.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Paginated list of requests
            ///
            /// - Remark: Generated from `#/paths//requests/get(listRequests)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.listRequests.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            package var ok: Operations.listRequests.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Missing or invalid authentication
            ///
            /// - Remark: Generated from `#/paths//requests/get(listRequests)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Components.Responses.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            package var unauthorized: Components.Responses.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen package enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            package init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            package var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            package static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Submit a new feature request
    ///
    /// - Remark: HTTP `POST /requests`.
    /// - Remark: Generated from `#/paths//requests/post(submitRequest)`.
    package enum submitRequest {
        package static let id: Swift.String = "submitRequest"
        package struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/requests/POST/header`.
            package struct Headers: Sendable, Hashable {
                package var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.submitRequest.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                package init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.submitRequest.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            package var headers: Operations.submitRequest.Input.Headers
            /// - Remark: Generated from `#/paths/requests/POST/requestBody`.
            @frozen package enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/requests/POST/requestBody/json`.
                package struct jsonPayload: Codable, Hashable, Sendable {
                    /// - Remark: Generated from `#/paths/requests/POST/requestBody/json/title`.
                    package var title: Swift.String
                    /// - Remark: Generated from `#/paths/requests/POST/requestBody/json/body`.
                    package var body: Swift.String
                    /// Creates a new `jsonPayload`.
                    ///
                    /// - Parameters:
                    ///   - title:
                    ///   - body:
                    package init(
                        title: Swift.String,
                        body: Swift.String
                    ) {
                        self.title = title
                        self.body = body
                    }
                    package enum CodingKeys: String, CodingKey {
                        case title
                        case body
                    }
                }
                /// - Remark: Generated from `#/paths/requests/POST/requestBody/content/application\/json`.
                case json(Operations.submitRequest.Input.Body.jsonPayload)
            }
            package var body: Operations.submitRequest.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            package init(
                headers: Operations.submitRequest.Input.Headers = .init(),
                body: Operations.submitRequest.Input.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen package enum Output: Sendable, Hashable {
            package struct Created: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/requests/POST/responses/201/content`.
                @frozen package enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/requests/POST/responses/201/content/application\/json`.
                    case json(Components.Schemas.Request)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    package var json: Components.Schemas.Request {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                package var body: Operations.submitRequest.Output.Created.Body
                /// Creates a new `Created`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                package init(body: Operations.submitRequest.Output.Created.Body) {
                    self.body = body
                }
            }
            /// Request created
            ///
            /// - Remark: Generated from `#/paths//requests/post(submitRequest)/responses/201`.
            ///
            /// HTTP response code: `201 created`.
            case created(Operations.submitRequest.Output.Created)
            /// The associated value of the enum case if `self` is `.created`.
            ///
            /// - Throws: An error if `self` is not `.created`.
            /// - SeeAlso: `.created`.
            package var created: Operations.submitRequest.Output.Created {
                get throws {
                    switch self {
                    case let .created(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "created",
                            response: self
                        )
                    }
                }
            }
            /// Validation error
            ///
            /// - Remark: Generated from `#/paths//requests/post(submitRequest)/responses/400`.
            ///
            /// HTTP response code: `400 badRequest`.
            case badRequest(Components.Responses.BadRequest)
            /// The associated value of the enum case if `self` is `.badRequest`.
            ///
            /// - Throws: An error if `self` is not `.badRequest`.
            /// - SeeAlso: `.badRequest`.
            package var badRequest: Components.Responses.BadRequest {
                get throws {
                    switch self {
                    case let .badRequest(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "badRequest",
                            response: self
                        )
                    }
                }
            }
            /// Missing or invalid authentication
            ///
            /// - Remark: Generated from `#/paths//requests/post(submitRequest)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Components.Responses.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            package var unauthorized: Components.Responses.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen package enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            package init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            package var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            package static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Search requests by title
    ///
    /// - Remark: HTTP `GET /requests/search`.
    /// - Remark: Generated from `#/paths//requests/search/get(searchRequests)`.
    package enum searchRequests {
        package static let id: Swift.String = "searchRequests"
        package struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/requests/search/GET/query`.
            package struct Query: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/requests/search/GET/query/q`.
                package var q: Swift.String
                /// - Remark: Generated from `#/paths/requests/search/GET/query/limit`.
                package var limit: Swift.Int?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - q:
                ///   - limit:
                package init(
                    q: Swift.String,
                    limit: Swift.Int? = nil
                ) {
                    self.q = q
                    self.limit = limit
                }
            }
            package var query: Operations.searchRequests.Input.Query
            /// - Remark: Generated from `#/paths/requests/search/GET/header`.
            package struct Headers: Sendable, Hashable {
                package var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.searchRequests.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                package init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.searchRequests.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            package var headers: Operations.searchRequests.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - headers:
            package init(
                query: Operations.searchRequests.Input.Query,
                headers: Operations.searchRequests.Input.Headers = .init()
            ) {
                self.query = query
                self.headers = headers
            }
        }
        @frozen package enum Output: Sendable, Hashable {
            package struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/requests/search/GET/responses/200/content`.
                @frozen package enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/requests/search/GET/responses/200/content/application\/json`.
                    case json([Components.Schemas.Request])
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    package var json: [Components.Schemas.Request] {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                package var body: Operations.searchRequests.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                package init(body: Operations.searchRequests.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Matching requests
            ///
            /// - Remark: Generated from `#/paths//requests/search/get(searchRequests)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.searchRequests.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            package var ok: Operations.searchRequests.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Validation error
            ///
            /// - Remark: Generated from `#/paths//requests/search/get(searchRequests)/responses/400`.
            ///
            /// HTTP response code: `400 badRequest`.
            case badRequest(Components.Responses.BadRequest)
            /// The associated value of the enum case if `self` is `.badRequest`.
            ///
            /// - Throws: An error if `self` is not `.badRequest`.
            /// - SeeAlso: `.badRequest`.
            package var badRequest: Components.Responses.BadRequest {
                get throws {
                    switch self {
                    case let .badRequest(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "badRequest",
                            response: self
                        )
                    }
                }
            }
            /// Missing or invalid authentication
            ///
            /// - Remark: Generated from `#/paths//requests/search/get(searchRequests)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Components.Responses.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            package var unauthorized: Components.Responses.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen package enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            package init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            package var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            package static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Get a single feature request
    ///
    /// - Remark: HTTP `GET /requests/{requestId}`.
    /// - Remark: Generated from `#/paths//requests/{requestId}/get(getRequest)`.
    package enum getRequest {
        package static let id: Swift.String = "getRequest"
        package struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/requests/{requestId}/GET/path`.
            package struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/requests/{requestId}/GET/path/requestId`.
                package var requestId: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - requestId:
                package init(requestId: Swift.String) {
                    self.requestId = requestId
                }
            }
            package var path: Operations.getRequest.Input.Path
            /// - Remark: Generated from `#/paths/requests/{requestId}/GET/header`.
            package struct Headers: Sendable, Hashable {
                package var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.getRequest.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                package init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.getRequest.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            package var headers: Operations.getRequest.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            package init(
                path: Operations.getRequest.Input.Path,
                headers: Operations.getRequest.Input.Headers = .init()
            ) {
                self.path = path
                self.headers = headers
            }
        }
        @frozen package enum Output: Sendable, Hashable {
            package struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/requests/{requestId}/GET/responses/200/content`.
                @frozen package enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/requests/{requestId}/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.Request)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    package var json: Components.Schemas.Request {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                package var body: Operations.getRequest.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                package init(body: Operations.getRequest.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Request details
            ///
            /// - Remark: Generated from `#/paths//requests/{requestId}/get(getRequest)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.getRequest.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            package var ok: Operations.getRequest.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            package struct MovedPermanently: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/requests/{requestId}/GET/responses/301/content`.
                @frozen package enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/requests/{requestId}/GET/responses/301/content/json`.
                    package struct jsonPayload: Codable, Hashable, Sendable {
                        /// - Remark: Generated from `#/paths/requests/{requestId}/GET/responses/301/content/json/mergedIntoId`.
                        package var mergedIntoId: Swift.String
                        /// Creates a new `jsonPayload`.
                        ///
                        /// - Parameters:
                        ///   - mergedIntoId:
                        package init(mergedIntoId: Swift.String) {
                            self.mergedIntoId = mergedIntoId
                        }
                        package enum CodingKeys: String, CodingKey {
                            case mergedIntoId
                        }
                    }
                    /// - Remark: Generated from `#/paths/requests/{requestId}/GET/responses/301/content/application\/json`.
                    case json(Operations.getRequest.Output.MovedPermanently.Body.jsonPayload)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    package var json: Operations.getRequest.Output.MovedPermanently.Body.jsonPayload {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                package var body: Operations.getRequest.Output.MovedPermanently.Body
                /// Creates a new `MovedPermanently`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                package init(body: Operations.getRequest.Output.MovedPermanently.Body) {
                    self.body = body
                }
            }
            /// Request was merged into another
            ///
            /// - Remark: Generated from `#/paths//requests/{requestId}/get(getRequest)/responses/301`.
            ///
            /// HTTP response code: `301 movedPermanently`.
            case movedPermanently(Operations.getRequest.Output.MovedPermanently)
            /// The associated value of the enum case if `self` is `.movedPermanently`.
            ///
            /// - Throws: An error if `self` is not `.movedPermanently`.
            /// - SeeAlso: `.movedPermanently`.
            package var movedPermanently: Operations.getRequest.Output.MovedPermanently {
                get throws {
                    switch self {
                    case let .movedPermanently(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "movedPermanently",
                            response: self
                        )
                    }
                }
            }
            /// Missing or invalid authentication
            ///
            /// - Remark: Generated from `#/paths//requests/{requestId}/get(getRequest)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Components.Responses.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            package var unauthorized: Components.Responses.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Resource not found
            ///
            /// - Remark: Generated from `#/paths//requests/{requestId}/get(getRequest)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            case notFound(Components.Responses.NotFound)
            /// The associated value of the enum case if `self` is `.notFound`.
            ///
            /// - Throws: An error if `self` is not `.notFound`.
            /// - SeeAlso: `.notFound`.
            package var notFound: Components.Responses.NotFound {
                get throws {
                    switch self {
                    case let .notFound(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "notFound",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen package enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            package init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            package var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            package static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Vote on a feature request
    ///
    /// - Remark: HTTP `POST /requests/{requestId}/vote`.
    /// - Remark: Generated from `#/paths//requests/{requestId}/vote/post(vote)`.
    package enum vote {
        package static let id: Swift.String = "vote"
        package struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/requests/{requestId}/vote/POST/path`.
            package struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/requests/{requestId}/vote/POST/path/requestId`.
                package var requestId: Swift.String
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - requestId:
                package init(requestId: Swift.String) {
                    self.requestId = requestId
                }
            }
            package var path: Operations.vote.Input.Path
            /// - Remark: Generated from `#/paths/requests/{requestId}/vote/POST/header`.
            package struct Headers: Sendable, Hashable {
                package var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.vote.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                package init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.vote.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            package var headers: Operations.vote.Input.Headers
            /// - Remark: Generated from `#/paths/requests/{requestId}/vote/POST/requestBody`.
            @frozen package enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/requests/{requestId}/vote/POST/requestBody/json`.
                package struct jsonPayload: Codable, Hashable, Sendable {
                    /// 1 = upvote, -1 = downvote, 0 = remove vote
                    ///
                    /// - Remark: Generated from `#/paths/requests/{requestId}/vote/POST/requestBody/json/value`.
                    @frozen package enum valuePayload: Int, Codable, Hashable, Sendable, CaseIterable {
                        case _1 = 1
                        case _n1 = -1
                        case _0 = 0
                    }
                    /// 1 = upvote, -1 = downvote, 0 = remove vote
                    ///
                    /// - Remark: Generated from `#/paths/requests/{requestId}/vote/POST/requestBody/json/value`.
                    package var value: Operations.vote.Input.Body.jsonPayload.valuePayload
                    /// Creates a new `jsonPayload`.
                    ///
                    /// - Parameters:
                    ///   - value: 1 = upvote, -1 = downvote, 0 = remove vote
                    package init(value: Operations.vote.Input.Body.jsonPayload.valuePayload) {
                        self.value = value
                    }
                    package enum CodingKeys: String, CodingKey {
                        case value
                    }
                }
                /// - Remark: Generated from `#/paths/requests/{requestId}/vote/POST/requestBody/content/application\/json`.
                case json(Operations.vote.Input.Body.jsonPayload)
            }
            package var body: Operations.vote.Input.Body
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            ///   - body:
            package init(
                path: Operations.vote.Input.Path,
                headers: Operations.vote.Input.Headers = .init(),
                body: Operations.vote.Input.Body
            ) {
                self.path = path
                self.headers = headers
                self.body = body
            }
        }
        @frozen package enum Output: Sendable, Hashable {
            package struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/requests/{requestId}/vote/POST/responses/200/content`.
                @frozen package enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/requests/{requestId}/vote/POST/responses/200/content/application\/json`.
                    case json(Components.Schemas.Vote)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    package var json: Components.Schemas.Vote {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                package var body: Operations.vote.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                package init(body: Operations.vote.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Vote recorded
            ///
            /// - Remark: Generated from `#/paths//requests/{requestId}/vote/post(vote)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.vote.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            package var ok: Operations.vote.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Missing or invalid authentication
            ///
            /// - Remark: Generated from `#/paths//requests/{requestId}/vote/post(vote)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Components.Responses.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            package var unauthorized: Components.Responses.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Resource not found
            ///
            /// - Remark: Generated from `#/paths//requests/{requestId}/vote/post(vote)/responses/404`.
            ///
            /// HTTP response code: `404 notFound`.
            case notFound(Components.Responses.NotFound)
            /// The associated value of the enum case if `self` is `.notFound`.
            ///
            /// - Throws: An error if `self` is not `.notFound`.
            /// - SeeAlso: `.notFound`.
            package var notFound: Components.Responses.NotFound {
                get throws {
                    switch self {
                    case let .notFound(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "notFound",
                            response: self
                        )
                    }
                }
            }
            package struct TooManyRequests: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/requests/{requestId}/vote/POST/responses/429/headers`.
                package struct Headers: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/requests/{requestId}/vote/POST/responses/429/headers/Retry-After`.
                    package var Retry_hyphen_After: Swift.Int?
                    /// Creates a new `Headers`.
                    ///
                    /// - Parameters:
                    ///   - Retry_hyphen_After:
                    package init(Retry_hyphen_After: Swift.Int? = nil) {
                        self.Retry_hyphen_After = Retry_hyphen_After
                    }
                }
                /// Received HTTP response headers
                package var headers: Operations.vote.Output.TooManyRequests.Headers
                /// - Remark: Generated from `#/paths/requests/{requestId}/vote/POST/responses/429/content`.
                @frozen package enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/requests/{requestId}/vote/POST/responses/429/content/application\/json`.
                    case json(Components.Schemas.ApiError)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    package var json: Components.Schemas.ApiError {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                package var body: Operations.vote.Output.TooManyRequests.Body
                /// Creates a new `TooManyRequests`.
                ///
                /// - Parameters:
                ///   - headers: Received HTTP response headers
                ///   - body: Received HTTP response body
                package init(
                    headers: Operations.vote.Output.TooManyRequests.Headers = .init(),
                    body: Operations.vote.Output.TooManyRequests.Body
                ) {
                    self.headers = headers
                    self.body = body
                }
            }
            /// Rate limited
            ///
            /// - Remark: Generated from `#/paths//requests/{requestId}/vote/post(vote)/responses/429`.
            ///
            /// HTTP response code: `429 tooManyRequests`.
            case tooManyRequests(Operations.vote.Output.TooManyRequests)
            /// The associated value of the enum case if `self` is `.tooManyRequests`.
            ///
            /// - Throws: An error if `self` is not `.tooManyRequests`.
            /// - SeeAlso: `.tooManyRequests`.
            package var tooManyRequests: Operations.vote.Output.TooManyRequests {
                get throws {
                    switch self {
                    case let .tooManyRequests(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "tooManyRequests",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen package enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            package init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            package var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            package static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// List decline reasons for the app
    ///
    /// - Remark: HTTP `GET /decline-reasons`.
    /// - Remark: Generated from `#/paths//decline-reasons/get(listDeclineReasons)`.
    package enum listDeclineReasons {
        package static let id: Swift.String = "listDeclineReasons"
        package struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/decline-reasons/GET/header`.
            package struct Headers: Sendable, Hashable {
                package var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.listDeclineReasons.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                package init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.listDeclineReasons.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            package var headers: Operations.listDeclineReasons.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            package init(headers: Operations.listDeclineReasons.Input.Headers = .init()) {
                self.headers = headers
            }
        }
        @frozen package enum Output: Sendable, Hashable {
            package struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/decline-reasons/GET/responses/200/content`.
                @frozen package enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/decline-reasons/GET/responses/200/content/application\/json`.
                    case json([Components.Schemas.DeclineReason])
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    package var json: [Components.Schemas.DeclineReason] {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                package var body: Operations.listDeclineReasons.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                package init(body: Operations.listDeclineReasons.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// List of decline reasons
            ///
            /// - Remark: Generated from `#/paths//decline-reasons/get(listDeclineReasons)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.listDeclineReasons.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            package var ok: Operations.listDeclineReasons.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Missing or invalid authentication
            ///
            /// - Remark: Generated from `#/paths//decline-reasons/get(listDeclineReasons)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Components.Responses.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            package var unauthorized: Components.Responses.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen package enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            package init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            package var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            package static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
}
